/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/Button.vue')['default']
    Card: typeof import('./components/base/Card.vue')['default']
    Cell: typeof import('./components/base/Cell.vue')['default']
    Input: typeof import('./components/base/Input.vue')['default']
    NavBar: typeof import('./components/navigation/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./components/navigation/TabBar.vue')['default']
  }
}
